/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DeptManger: typeof import('./src/views/baseData/deptManger.vue')['default']
    DeptSet: typeof import('./src/views/setting/deptSet.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    GitPersonManger: typeof import('./src/views/baseData/gitPersonManger.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/views/homeView/home.vue')['default']
    HomeView: typeof import('./src/views/homeView/homeView.vue')['default']
    IconHomeCompany: typeof import('~icons/home/company')['default']
    IconIcBaseline5g: typeof import('~icons/ic/baseline5g')['default']
    IconIcBaseline5kPlus: typeof import('~icons/ic/baseline5k-plus')['default']
    Login: typeof import('./src/views/login/index.vue')['default']
    MainMsg: typeof import('./src/views/homeView/mainMsg.vue')['default']
    NavTop: typeof import('./src/views/login/components/navTop.vue')['default']
    NotFound: typeof import('./src/views/notFound.vue')['default']
    Page: typeof import('./src/components/Page/index.vue')['default']
    PersonManger: typeof import('./src/views/baseData/personManger.vue')['default']
    PersonSet: typeof import('./src/views/setting/personSet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    Vuex: typeof import('./src/views/vuex.vue')['default']
  }
}
